POST http://localhost:3001/api/blogs
Content-Type: application/json


{
"title": "Food Blog",
"author": "Food Lover",
"url": "http://www.foodblog.com",
"likes": 8
}

# GET http://localhost:3001/api/blogs